ESP_INIT_VALUE=1
OLED_SDA=6
OLED_SCL=7
OLED_ADDR=0x3c
DHT_PIN=5
DHT_TEMP=-1
DHT_HUM=0
MQQT_USER="esp"
MQQT_PWD="esp12e"
MQQT_SERVER="<localmqqt>"
MQQT_PORT=1883
MQQT_MESS=""
WIFI_SSID="<Wifi SSID>"
WIFI_PWD="<Wifi Pwd>"
TIMER1_UPDATE=60000

