FROM ubuntu:16.04
LABEL MAINTAINER="Aurelien Bruno <aurelbruno06@gmail.com>"
RUN apt-get autoremove && apt-get update && apt-get upgrade -y && apt-get install -y nginx && rm -rf /var/lib/apt/lists/* 

